version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: hotelbooking-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotelbookingdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: TestPassword123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotelbooking-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=hotelbookingdb;User=test_user;Password=TestPassword123!;"
    ports:
      - "5232:8080"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: hotelbooking-web
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  mysql_data:
